// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYJy6UOuzKD8xNiyyz7awiUSvqDN9WITI',
    appId: '1:497558927491:web:bd4dc2dc2f353d87ce43b6',
    messagingSenderId: '497558927491',
    projectId: 'mave-app-7787e',
    authDomain: 'mave-app-7787e.firebaseapp.com',
    storageBucket: 'mave-app-7787e.firebasestorage.app',
    measurementId: 'G-33FF4DXPCJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvk7MicJUBGPkf3i-yBQzZmeWzWrvSx5c',
    appId: '1:497558927491:android:072d9987a40b1ea8ce43b6',
    messagingSenderId: '497558927491',
    projectId: 'mave-app-7787e',
    storageBucket: 'mave-app-7787e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHWVWJncD7O7MQQj_8iulTvYYe4x1S2Bg',
    appId: '1:497558927491:ios:ebca9089ed33f33cce43b6',
    messagingSenderId: '497558927491',
    projectId: 'mave-app-7787e',
    storageBucket: 'mave-app-7787e.firebasestorage.app',
    iosBundleId: 'com.mave.mave2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHWVWJncD7O7MQQj_8iulTvYYe4x1S2Bg',
    appId: '1:497558927491:ios:ebca9089ed33f33cce43b6',
    messagingSenderId: '497558927491',
    projectId: 'mave-app-7787e',
    storageBucket: 'mave-app-7787e.firebasestorage.app',
    iosBundleId: 'com.mave.mave2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBYJy6UOuzKD8xNiyyz7awiUSvqDN9WITI',
    appId: '1:497558927491:web:81d9a18c8784bfe7ce43b6',
    messagingSenderId: '497558927491',
    projectId: 'mave-app-7787e',
    authDomain: 'mave-app-7787e.firebaseapp.com',
    storageBucket: 'mave-app-7787e.firebasestorage.app',
    measurementId: 'G-0SZDLXFR9N',
  );
}
